---

- name: Bring servers up to date.
  hosts: All
  become: true
  pre_tasks:

    - name: Patch servers
      tags: always
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoclean: true
        autoremove: true

- name: Install base packages and secure proxmox cluster.
  hosts: proxmox_cluster
  gather_facts: true
  become: true
  roles:
    - role: base_linux_server

- name: Secure and install docker engine on docker servers.
  hosts: docker_containers
  gather_facts: true
  become: true
  tags: docker
  roles:
    - role: base_linux_server

- name: Deploy containers
  hosts: docker_server01
  gather_facts: false
  become: true
  pre_tasks:
    - name: Kill and remove previous containers
      community.docker.docker_compose_v2:
        project_src: /srv/
        check_files_existing: false
        state: absent
        remove_images: all
        remove_orphans: true

  roles:
    - role: pihole
    - role: vaultwarden
    - role: wg-easy
    - role: home_assistant

  tasks:
    - name: Add Compose files to .env
      ansible.builtin.script:
        cmd: scripts/compose.sh
        chdir: /srv/

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: /srv/
        check_files_existing: false
        pull: always
        state: present
