---

- name: Bring servers up to date.
  hosts: All
  become: true
  pre_tasks:

    - name: Patch servers
      tags: always
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoclean: true
        autoremove: true

- name: Install base packages and secure proxmox cluster.
  hosts: proxmox_cluster
  gather_facts: true
  become: true
  roles:
    - role: base_linux_server

- name: Secure and install docker engine on docker servers.
  hosts: Docker_containers
  gather_facts: true
  become: true
  tags: docker
  roles:
    - role: base_linux_server

- name: Deploy containers
  hosts: docker_server01
  gather_facts: false
  become: true
  roles:
    - role: pihole
    - role: vaultwarden
    - role: wg-easy
    - role: traefik

  tasks:
    - name: Add Compose files to .env
      ansible.builtin.script:
        cmd: scripts/compose.sh
        chdir: /home/mitchell/server

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: /home/mitchell/server
        check_files_existing: false
        pull: always
        build: always
        state: present

- name: Deploy conatiners
  hosts: docker_server01
  gather_facts: false
  become: true
  roles:
    
    

  tasks:
    - name: Add Compose files to .env
      ansible.builtin.script:
        cmd: scripts/compose.sh
        chdir: /home/mitchell/server

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: /home/mitchell/server
        check_files_existing: false
        pull: always
        build: always
        state: present
