- name: create groups group
  group:
    name: admin
    state: present

- name: add local non-root user
  user: 
    name: "{{ username }}"
    groups: 
      - admin
      - users
    shell: /bin/bash
    home: /home/{{ username }}
    create_home: yes
    state: present

- name: add ansible user
  user:
    name: "{{ ansible_username }}"

- name: add SSH key for user
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

- name: ensure sudo is installed
  package:
    name: sudo
    state: present
  when: ansible_facts['hostname'] != "truenas"

- name: Add local user to sudoers
  template:
    dest: /etc/sudoers.d/{{ username }}
    src: admin_sudo.j2
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s

- name: add ansible user to sudoers
  template:
    src: ansible_sudo.j2
    dest: /etc/sudoers.d/{{ ansible_username }}
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s