- name: Create groups group
  ansible.builtin.group:
    name: admin
    state: present

- name: Add local non-root user
  ansible.builtin.user:
    name: "{{ base_linux_server_username }}"
    groups:
      - admin
      - users
    shell: /bin/bash
    home: /home/{{ base_linux_server_username }}
    create_home: true
    state: present

- name: Add ansible user
  ansible.builtin.user:
    name: "{{ base_linux_server_ansible_username }}"

- name: Add SSH key for user
  ansible.posix.authorized_key:
    user: "{{ base_linux_server_username }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

- name: Add local user to sudoers
  ansible.builtin.template:
    dest: /etc/sudoers.d/{{ base_linux_server_username }}
    src: admin_sudo.j2
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s

- name: Add ansible user to sudoers
  ansible.builtin.template:
    src: ansible_sudo.j2
    dest: /etc/sudoers.d/{{ base_linux_server_ansible_username }}
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s
