---
- name: Add Users and Groups
  ansible.builtin.include_tasks: add_users.yml

- name: Configure SSH
  ansible.builtin.include_tasks: ssh.yml

- name: Install Docker Engine
  ansible.builtin.include_tasks: docker_engine.yml
  when: ansible_facts['distribution'] != "Debian"

# - include_tasks: ufw.yml
#   when: ansible_facts['distribution'] not in ["RedHat", "Debian"]
- name: Add remote banner
  tags: security
  ansible.builtin.copy:
    dest: /etc/issue.net
    src: issue
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Add local banner
  tags: security
  ansible.builtin.copy:
    dest: /etc/issue
    src: issue
    owner: root
    group: root
    mode: "0644"
    backup: true
