---
- name: Add Users and Groups
  ansible.builtin.include_tasks: add_users.yml

- name: Configure SSH
  ansible.builtin.include_tasks: ssh.yml

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_version
  failed_when: false
  changed_when: false

- name: Show Docker installation status
  ansible.builtin.debug:
    msg: "Docker is installed. Version: {{ docker_version.stdout }}"
  when: docker_version.rc == 0

- name: Install Docker Engine
  ansible.builtin.include_tasks: docker_engine.yml
  when: ansible_facts['distribution'] != "Debian" and docker_version.rc !=0

- name: Add remote banner
  tags: security
  ansible.builtin.copy:
    dest: /etc/issue.net
    src: issue
    owner: root
    group: root
    mode: "0644"
    backup: true

- name: Add local banner
  tags: security
  ansible.builtin.copy:
    dest: /etc/issue
    src: issue
    owner: root
    group: root
    mode: "0644"
    backup: true
