- name: Add hardened SSH config (non-proxmox hosts)
  tags: security
  ansible.builtin.template:
    dest: /etc/ssh/sshd_config
    src: sshd_config.j2
    owner: root
    group: root
    mode: "0600"
    backup: true
  when: "'pve' not in ansible_facts['hostname']"

- name: Restart SSH (debian_based)
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ansible_facts['distribution'] != "RedHat"

- name: Restart SSH (redhat)
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: ansible_facts['distribution'] == "RedHat"
