- name: Ensure ufw is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow servers to be ssh'd into.
  community.general.ufw:
    rule: limit
    port: 22
    from_ip: 10.5.15.0/24
    comment: allow SSH from internal network.

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Set default incoming to deny
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Set default routed to deny
  community.general.ufw:
    policy: deny
    direction: routed
