- name: Create baby_buddy and config directories
  ansible.builtin.file:
    dest: /srv/baby_buddy/config/
    state: directory
    mode: "0600"
    modification_time: preserve
    access_time: preserve

- name: Copy docker-compose.yaml
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /srv/docker-compose-baby-buddy.yaml
    mode: "0755"
