- name: Create home_assistant and config directories
  ansible.builtin.file:
    dest: /srv/home_assistant/config/
    state: directory
    mode: "0600"
    modification_time: preserve
    access_time: preserve

- name: Copy docker-compose.yaml
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /srv/docker-compose-home-assistant.yaml
    mode: "0755"
